
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[vi_SHOHIN_IMG_FILE_2]') AND type in (N'V'))
DROP VIEW [dbo].[vi_SHOHIN_IMG_FILE_2]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[vi_SHOHIN_IMG_FILE_2]
AS
WITH
	t1 AS (
		SELECT SSHM_HTCD,
			SSHM_SCD,
			SSHM_SFILENAME,
			SSHM_BUMONCD,
			SSHM_SHONAME,
			SSHM_JANCD1,
			SSHM_SURYOSEIGEN,
			SSHM_KEISAIFLG
		FROM  ft_SHOHIN_MST(NULL)
		WHERE  SSHM_JUCHUEND >= CAST(GETDATE() AS date)
			AND SSHM_HAIEND >= CAST(GETDATE() AS date)
	)
SELECT
	t2.SIF_PIC_UNIT,
	t1.SSHM_HTCD,
	t1.SSHM_SCD,
	t1.SSHM_SFILENAME,
	t1.SSHM_BUMONCD,
	t1.SSHM_SHONAME,
	t1.SSHM_JANCD1,
	t1.SSHM_SURYOSEIGEN,
	t1.SSHM_KEISAIFLG,
	t2.IMG, t2.PATH_IMG,
	t2.DTL_IMG, t2.PATH_DTL_IMG,
	t2.KLS_IMG, t2.PATH_KLS_IMG,
	t2.SIF_YMD
FROM t1
INNER JOIN vi_SHOHIN_IMG_FILE_1 t2
ON t1.SSHM_SCD = t2.SIF_SCD
	AND t1.SSHM_SFILENAME = t2.SIF_SFILENAME

GO
